#H2
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;
    username: sa
    password:
    driver-class-name: org.h2.Driver

#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: hoseo
#    password: 1234

  #JPA
  jpa:
    hibernate:
      ddl-auto: create #테이블 자동 생성
    properties:
      hibernate:
        #show_sql: true   #운영할 때는 system.out로 sql를 보여주기때문에 쓰지 말아야한다
        format_sql: true  #sql 이쁘게 보이게
        default_batch_fetch_size: 100
#database:
        ##      platform: org.hibernate.dialect.Oracle11gDialect

#  #페이징 20 -> 10변경
#  data:
#    web:
#      pageable:
#        default-page-size: 2
#    #    :open-in-view: false

logging:
  level:
    org.hibernate.sql: debug
    #org.hibernate.type: trace
#    org.springframework.security: debug
    #root : debug

