##로그인
POST http://localhost:8080/api/members/login
Content-Type: application/json

{"username":"storeadmin","password":"1234"}

### accessToken 재발급
POST http://localhost:8080/api/members/refreshToken
Content-Type: application/json

{"grantType":"refreshToken","refreshToken":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtZW1iZXIxIiwicm9sZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2MTgxNTQ0Mjd9.ll5Ddvso7kIFWiWpHanyAnFLGp4Seq2T0XhkfmlII74"}

###회원 가입 테스트
POST http://localhost:8080/api/members/new
Content-Type: application/json

{"username":"test", "password":"1234", "name":"이범준", "phoneNum":"2323", "email": "dd@dd"}

### GET test
GET http://localhost:8080/api/members/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2MjIxNTM3ODl9.zko-_nNbdA9P-Kk60Pk8Y8SSZKDFwL3_RglILOTfGYo

###회원 번호표 조회 테스트
GET http://localhost:8080/api/members/tickets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2MjIxNTM3ODl9.zko-_nNbdA9P-Kk60Pk8Y8SSZKDFwL3_RglILOTfGYo



###회원 번호표 취소 테스트
DELETE http://localhost:8080/api/members/tickets
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlXyI6WyJST0xFX1VTRVIiXSwiaXNzIjoibGVlYmVvbWp1biIsImV4cCI6MTYxMjE1MDcwOSwidXNlcm5hbWUiOiJ0ZXN0In0.Xf1PYM6gt8gTRMqrYcILMKspy6Ars7LhbW2aXJeDTvs

### 회원 정보 조회
GET http://localhost:8080/api/members/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdG9yZWFkbWluIiwicm9sZXMiOiJST0xFX1NUT1JFX0FETUlOIiwiZXhwIjoxNjIyMjE3MTc2fQ.0bSKFJpoS0lvB6jQjCz-qxLXpC32xLJDfhT5j4gWLa0

