###번호표 뽑기 테스트
POST http://localhost:8080/api/stores/2/tickets/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2MjIxNTM3ODl9.zko-_nNbdA9P-Kk60Pk8Y8SSZKDFwL3_RglILOTfGYo



{"peopleCount":"5"}

###[관리자]대기중인 번호표 + 가게 현황 보기
#GET http://localhost:8080/api/stores/tickets
GET http://localhost:8080/api/stores/tickets?page=1&size=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2MjIxNTM3ODl9.zko-_nNbdA9P-Kk60Pk8Y8SSZKDFwL3_RglILOTfGYo

###[관리자]전체 번호표 보기
#GET http://localhost:8080/api/stores/tickets
GET http://localhost:8080/api/stores/tickets/holding
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlXyI6WyJST0xFX1NUT1JFX0FETUlOIl0sImlzcyI6ImxlZWJlb21qdW4iLCJleHAiOjE2MTEwOTA3NjEsInVzZXJuYW1lIjoiYWRtaW4ifQ.LP91duF0BuPCq4zOZ8FimxK-ciOqc7jUxl0jgFnECpk

###[관리자]번호표 취소 하기
POST http://localhost:8080/api/stores/tickets/24/cancel-ticket
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdG9yZWFkbWluIiwicm9sZXMiOiJST0xFX1NUT1JFX0FETUlOIiwiZXhwIjoxNjIyMTU0MDc3fQ.GjZ-nPSFuOhRv1Fb-b1jBbSYbm99aK-zrdPrjNlFhgo

###[관리자]번호표 체크 하기
POST http://localhost:8080/api/stores/tickets/26/check-ticket
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdG9yZWFkbWluIiwicm9sZXMiOiJST0xFX1NUT1JFX0FETUlOIiwiZXhwIjoxNjIyMTU0MDc3fQ.GjZ-nPSFuOhRv1Fb-b1jBbSYbm99aK-zrdPrjNlFhgo

###[관리자]번호표 보류 하기
POST http://localhost:8080/api/stores/tickets/8/hold-ticket
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdG9yZWFkbWluIiwicm9sZXMiOiJST0xFX1NUT1JFX0FETUlOIiwiZXhwIjoxNjIyMTU0MDc3fQ.GjZ-nPSFuOhRv1Fb-b1jBbSYbm99aK-zrdPrjNlFhgo

###[관리자]번호표 보류 취소 하기
POST http://localhost:8080/api/stores/tickets/10/cancel-holdingTicket
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdG9yZWFkbWluIiwicm9sZXMiOiJST0xFX1NUT1JFX0FETUlOIiwiZXhwIjoxNjIyMTU0MDc3fQ.GjZ-nPSFuOhRv1Fb-b1jBbSYbm99aK-zrdPrjNlFhgo

###[관리자]번호표 보류 체크 하기
POST http://localhost:8080/api/stores/tickets/6/check-holdingTicket
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdG9yZWFkbWluIiwicm9sZXMiOiJST0xFX1NUT1JFX0FETUlOIiwiZXhwIjoxNjIyMTU0MDc3fQ.GjZ-nPSFuOhRv1Fb-b1jBbSYbm99aK-zrdPrjNlFhgo